### ISSUE TITLE
Survey not being reflected on DHIS2

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1477]
Looks like a user sent 5 surveys and only 4 of them reached the server.

I'll add the exact text of the issue in a comment

**Comment by ifoche** [comment]
Mozambique started the data collection using HNQIS last week, with everything, we are with a small problem, were evaluated five (5) Franchise of the Four (4) Franchises it is possible to visualize the data in Graphs, the Franchise of Chamaculo is not being Possible to visualize, all the steps have been completed.
See the attachments.

![survey_disappeared](https://cloud.githubusercontent.com/assets/10931645/26463745/a3bfd0e4-4185-11e7-83e3-11346cca466c.png)
![screenshot_20170512-144642](https://cloud.githubusercontent.com/assets/10931645/26463752/a8ced63e-4185-11e7-950b-a5898056d71c.png)

**Comment by idelcano** [comment]
This problem will be solved in #1479
