### ISSUE TITLE
Blank fragment

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1695]

**Comment by ifoche** [comment]
Example [here](https://camo.githubusercontent.com/d796a6349066a8705be3b0aff20e38a06000a28f/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f62756464796275696c642d73637265656e73686f74732f3536623430386164363563353637303130306164663464662f3561303262653561343638653939303030313633633865302f33363434626263642d336630642d346336342d396534312d3366313438653133633361352e6a7067)

**Comment by ifoche** [comment]
More clues, they've been able to reproduce it when going to the improve module from sharing an assessment in formatted text

**Comment by manuelplazaspalacio** [comment]
Test in Android 4.4  when you change quickly  between tabs, changing orgunits in spinners, scheduling surveys... The tab bar blocks in a position and puts the rest of the screen in blank.

**Comment by idelcano** [comment]
I continued this issue in #1786
