### ISSUE TITLE
Completion chart not working

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1700]
Some examples:
- [Example 1](https://camo.githubusercontent.com/134ef41282281f157015ca1a74ff2c8a692223bb/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f62756464796275696c642d73637265656e73686f74732f3536623430386164363563353637303130306164663464662f3561303262653561343638653939303030313633633865302f30333536396339642d616132612d343363332d626231302d3963343730623937353738362e6a7067)
- [Example 2](https://user-images.githubusercontent.com/12784825/33232443-772dfb8c-d217-11e7-978f-8df7530dfdd9.png)
- [Example 3](https://camo.githubusercontent.com/a0324f853ef035fff9bdb2173a3a74baf5d41a37/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f62756464796275696c642d73637265656e73686f74732f3536623430386164363563353637303130306164663464662f3561303262653561343638653939303030313633633865302f38326537643032342d376461632d346237382d393435352d3537356138383833386136372e6a7067)

We have [a DB](https://github.com/EyeSeeTea/QAApp/files/1505162/compressedData.zip) from a device experimenting this problem. Entering with those credentials to the server and importing the DB may help finding the bug

**Comment by xurxodev** [comment]
@ifoche links example 1 and example 2 not working

**Comment by xurxodev** [comment]
This issue may be invalidated by #1785
