### ISSUE TITLE
When a < symbol is used on feedback, it doesn't render

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1717]
Please see [this screenshot](https://user-images.githubusercontent.com/26415203/33883144-bca0ed6e-df4b-11e7-956c-e39e7d87c90f.jpg)

**Comment by manuelplazaspalacio** [comment]
We can't reproduce the issue.
We check the Data Element "KE HNQIS HIV.3LA-210-<50 percent" with uid:UsJch9GRVuc in data and android and looks it works correctly.

**Comment by ifoche** [comment]
Re-opening this issue as the alpha testers said that they saw this in 1.3. If you can please check it again but in 1.3, that would be fantastic
