### ISSUE TITLE
Investigate telescope & other bug reporting tools

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1747]

**Comment by ifoche** [comment]
Important links:
- https://github.com/mattprecious/telescope/
- https://appsamurai.com/8-crash-reporting-tools-for-ios-and-android-apps/
- https://www.captechconsulting.com/blogs/a-comparison-of-android-crash-reporting-tools

**Comment by Amejia481** [comment]
From what I could found, our best alternative is to use [Bugshaker Android](https://github.com/stkent/bugshaker-android) is an open source project that allows us to do exactly the same as [Telescope](https://github.com/mattprecious/telescope/) does, but it's  pretty easy to integrate to our existing source code.

[Telescope](https://github.com/mattprecious/telescope/) has a big drawback for us and it is integration, if we want to use it, we're going to be forced to add TelescopeLayout in every piece of UI (xml files).

To work we have to place a TelescopeLayout at the root of our hierarchy.



```
  <com.mattprecious.telescope.TelescopeLayout
      xmlns:android="http://schemas.android.com/apk/res/android"
      android:id="@+id/telescope"
      android:layout_width="match_parent"
      android:layout_height="match_parent">
   
 <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">
      <TextView
          style="@style/Widget.Telescope.Description"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:drawableTop="@drawable/two_finger_press"
          android:text="@string/additional_attachment_description"
          />
    </ScrollView>
  </com.mattprecious.telescope.TelescopeLayout>
```

With [Bugshaker Android](https://github.com/stkent/bugshaker-android) we only need to instantiate it in just one place our Application class

```
public class CustomApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        BugShaker.get(this)
                 .setEmailAddresses("someone@example.com")   // required
                 .setEmailSubjectLine("Custom Subject Line") // optional
                 .setAlertDialogType(AlertDialogType.NATIVE) // optional
                 .setLoggingEnabled(BuildConfig.DEBUG)       // optional
                 .setIgnoreFlagSecure(true)                  // optional
                 .assemble()                                 // required
                 .start();                                   // required
    }
}
```

**Important points**

We must be aware is that none of these projects allows us to add Locat logs by default, but we can add this behavior, as they are open source projects.

They only provide us a limited set of information about the device
```
Time Stamp: 2018-02-25T17:13:42 UTC
App Version: 1.4.1 (6)
Install Source: Google Play Store
Android Version: 7.1.1 (25)
Device Manufacturer: MOTOROLA
Device Model: MOTO E (4) PLUS
Display Resolution: 1184x720
Display Density (Actual): 320dpi
Display Density (Bucket) xhdpi
---------------------
```

[Bugshaker Android](https://github.com/stkent/bugshaker-android) their maintainers explicitly said that is not a project under active development and its development may resume in the future, but at least it last commit was on Dec 18, 2017, as oppose to [Telescope](https://github.com/mattprecious/telescope/) that it last commit was on Mar 23, 2017

**Comment by ifoche** [comment]
We finally chose bugshaker
