### ISSUE TITLE
Move share & complete buttons to the upper right corner

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1761]
See [this image](https://camo.githubusercontent.com/c0b41c911c277d5c64662a8c6dd0b50b5be1de7c/68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3536623336656130633538376465313330306238623536352f31323535313663363665383263373238616365323165306434366330626161623061623163336534636666626261346661623565663138303230343932393333323630326533333837383834663132646666343036653135316230303130626535643461316630366133613364633738653261343336363238663561353965396431366230633732633636653138616562383836316362663031626132323832346338366265656639383530643261613663376262336434643231363734346234373061383365643566333561613938346563393562663534396537346635366163313633653633663433622e706e67)

**Comment by Amejia481** [comment]
Needs #1759 first
