### ISSUE TITLE
Filters consistency

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1786]
Check the consistency among Surveys & OU filters across the modules. It seems that there are weird behaviors when moving from a module to another one in case we have a module still open / not finalized an action (i.e. Assess module still active, Improve module in a feedback or Monitor module with a OU selected).

**Comment by idelcano** [comment]
The actual filter workflow is:

Planning tab:
When selects a program(or all assessments && all org units), the org unit is unselect, and planning tab is shown.

When selects a org unit, the program is unselect, and PlanPerOrgUnitfragment is shown.

When enters with program+ou the OU is unselected and the tab shows the planning tab.
When enters with all assessment + ou, Planperorgunitfragment is shown.
When enters with program+All org, Planning is shown.

Assess:
All combinations shown the unsent list filtered.

Improve:
when enters with org unit and program, the survey feedback of that combination will be open.
When opens a feedback if you move to other tab or go back, the filter selection will be replaced by the survey´s org unit and program
Other combinations shown the sent list filtered.

Monitoring:
When the user enter with both filters(program+orgunit) the org unit filter will be unselected and the monitoring shows the pie filtered by program.

When select all assessment/all orgunits the monitoring show the main stats table.
Other combinations shows the pie filtered by programs or by org units.
