### ISSUE TITLE
Line chart is rendering with a very small size on Android 4.4

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1787]

**Comment by idelcano** [comment]
@ifoche  i couldn't replicate this problem, could you test it in the real device? thanks

**Comment by ifoche** [comment]
You're right. It's no longer happening. However, if you look at [this screenshot](https://drive.google.com/open?id=10dXik6LbPkDAYJ6fVJ53cUs4KQH6Id3j) you'll see that, at least in Android 4.4, there are no margins at all for the chart. Can you please fix that? Thank you!
