### ISSUE TITLE
Cancel Button Partially hiden on Dialog

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [ifoche/malariapp#1862]
## User Report
On Android 7.1.1, MotoE please see the attachment on the comments section

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot1902695307.jpg)
## Device Info
```
Time Stamp: 2018-04-08T18:57:42 UTC
App Version: 1.3.1 (42)
Install Source: Unknown
Android Version: 7.1.1 (25)
Device Manufacturer: MOTOROLA
Device Model: MOTO E (4) PLUS
Display Resolution: 1184x720
Display Density (Actual): 320dpi
Display Density (Bucket) xhdpi
---------------------

```

**Comment by Amejia481** [comment]
PrintScreen
![screenshot_20180408-150700](https://user-images.githubusercontent.com/773158/38471402-a8d12ec6-3b3e-11e8-8714-8c0384138f3e.png)
