### ISSUE TITLE
planperorgunit fragment is blank after hide and show planning

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [ifoche/malariapp#1867]
## User Report
after hidden and show planing. I go to plan and select program filter but planperorgunit fragment doesn't work

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot1824768871.jpg)
## Device Info
```
Time Stamp: 2018-04-09T07:16:39 UTC
App Version: 1.3.1 (42)
Install Source: Unknown
Android Version: 7.0 (24)
Device Manufacturer: XIAOMI
Device Model: REDMI NOTE 4
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by idelcano** [comment]
I try to solve using this branch: https://github.com/EyeSeeTea/malariapp/tree/feature-fix_plan_per_org_unit_fragment_blank
