### ISSUE TITLE
Reractor survey domain entity

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#1902]
This entity exists but is not used and It's an anemic entity:
Refactor survey to best practices and add all necessary changes only for being used for the pull, some tips:
* Avoid public setters by default, please read this article 
http://xurxodev.com/clean-architecture-code-smells-parte-2/
* create a constructor with mandatory fields
* create factory method to create an empty survey
- create factory method to create a pulled survey (with mandatory fields and values and composite scores)
* include values and composite scores as tree inside the survey
* add relations to other entities (program, orgunit etc..) by uid (no object reference) 
* add validations to mandatory info when a survey is created
* create unit tests
* **please analyze yourself more code to add or refactor**

**Comment by idelcano** [comment]
@xurxodev  i will modify the steps in this comment.

I created a 3 build factory methods to create 3 type of surveys. New survey, Pulled survey, and Planned survey, with his own validations.  I think the empty constructor is not necessary

- [x] create factory method to create an new survey
- [x] create factory method to create a pulled survey (with mandatory fields and values and composite scores)
- [x] create factory method to create a planned survey (with mandatory fields and values and composite scores)
- [ ] include values and composite scores as tree inside the survey
- [ ] add relations to other entities (program, orgunit etc..) by uid (no object reference)
- [x] add validations to mandatory info when a survey is created
- [x] create unit tests
- [ ] please analyze yourself more code to add or refactor
