### ISSUE TITLE
empty events bug

### ISSUE THREAD

**Issue by idelcano** [ifoche/malariapp#1928]
This bug causes a exception when the surveyChecker try to find a quarantine survey in the server to set as sent or as completed. 

This is caused by a server response with a empty event. 

The empty event is pushed when the user have a normal survey and a observation and plan action survey. 

The observation and plan action survey push wipe the sdk database during the normal survey push, and the events will pushed by the sdk without datavalues because the datavalues was setted in the middle of the push after get the empty events.

**Comment by xurxodev** [comment]
@idelcano please, can you add a description explaining this issue? thanks
