### ISSUE TITLE
Bring last modifications to next assessment date from 1.2 to 1.3

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1954]
Alpha testers are reporting that 1.3 still have problems to show the same next assessment date both in the shared Observation & action plan and the observation & action plan in the app. I think there were some last minute changes in 1.2 that were not migrated to 1.3.

**Comment by idelcano** [comment]
@ifoche I could not replicate.
The obsplanfragment show the completion date and the new assesment date(this is not visible in some devices) but the dates are the same in the fragment and in the shared text..
