### ISSUE TITLE
Refactor Composite Score calculation to domain

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#1971]
- [ ] Evaluate the possibility of moving the composite score calculation within the Survey, maybe that survey should not realize calculation but, should survey decide when to realize the calculation? please analyze.
- [ ] Create unit tests with different scenarios
- [ ] refactor fromSurveyEventMapper to create TrackedEntityValues during push process using CompositeScores and this code use currently ScoreRegister

**Comment by idelcano** [comment]
I think is possible refactor the composite score changing all the database models lists by domain entity lists.
If we have a survey with its list of questions, and with its list of questionValues(for that survey), we can solve some performance problems.
