### ISSUE TITLE
Analyze y create issues in backlog of refactor for decoupled PullDhisApiDataSource.

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#2002]
- Create an issue of refactor for a functional feature
- We should use SDK when be possible
- We should use current repositories, data sources
- We should use domain entities
- We should use use cases for every functional use case

parent of #2018
parent of  #2017
parent of  #2016

**Comment by idelcano** [comment]
parent of #2018,#2017,#2016
