### ISSUE TITLE
New design for feedback

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2030]
Please [see the mockup](https://camo.githubusercontent.com/23f05f665bbcd4a6a6b9c1a7f1028264a5161cd8/68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3536623336656130633538376465313330306238623536352f31323535313663363665383263373238616365323165306434366330626161623061623163336262386166666236353061313539623062653363343832323333326430316230323237373862613136346664353236393065303530613164653835333532346434316661616238643262613065353361373064393535303965646435366535663734633633663138616662623861346361643164613836326461313164316539653164333036393561613266326666353861383734353366316230373131383166643562333061323930346363623531653430362e6a706567)

**Comment by idelcano** [comment]
Please make all the cosmetics changes in hnqis variant to avoid future conflicts when merge this feature with development.
