### ISSUE TITLE
Videos not loading into the app

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2032]
Apparently, videos are configured for user MWdemo1; Malawidemo1 but they don't show. Please [have a look at the screenshot](https://user-images.githubusercontent.com/12784825/41453864-00e76d0c-7080-11e8-89ab-927507901077.png)

**Comment by idelcano** [comment]
@ifoche I tested with some phones.. after long pull, and the videos was downloaded successfully, connected by wifi.

maybe the alpha tester forgot the 4g restriction...

With 4g the videodownloader doesn't download any videos. 

Do you have more info? like the user db...

**Comment by ifoche** [comment]
closing it as apparently it won't be needed anymore
