### ISSUE TITLE
Analyze changes to work with dates in utc and in locale format to render in views. Create issues

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#2040]
parent to #2045
parent to #2046
parent to #2047
parent to #2048
parent to #2049
parent to #2050
parent to #2051

In dhis2 api all dates are with format yyyy-MM-dd'T'HH:mm:ss.SSS. We are pushing CDE dates (competionDate, CreatedDate) with format yyyy-MM-dd'T'HH:mm:ss.SSSZ.

In pull and push process, we need to review this because always we should work with dates in UTC without locale because to uniform dates used in dhis.

In the database, we should save all dates in utc
In domain we should  work with dates in utc
In presentation to render a date we should show it in converted to locale
In presentation to create a date should be in locale format but we shoud convert to domain and  save in database in utc

Analyze very well previously changes on this issue.

Create EPIC and related issues

**Comment by idelcano** [comment]
I started by testing a new control dataelement with date&time type(as some old control data elements) to test the event reports, and this type is required to use the date filters (in event reports).  

we need still pushing the controldataelement with "Date&time" type with "yyyy-MM-dd'T'HH:mm:ss.SSSZ" format. ( i tried other format with posman and the response was invalid format) 

Anyway we can use always UTC and send this date with SSS0 or similar.
