### ISSUE TITLE
Surveys appearing double in planning tab

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2107]
Please [see image](https://user-images.githubusercontent.com/26415203/44327634-d9f37d00-a467-11e8-9796-637e192bc522.jpg)

**Comment by ifoche** [comment]
DB here: [compressedData (35).zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46eb9b97339086ba9cecbb67a549f1d46115723a6b48e13b628ae92dbc56395b4d5a4afa49090c4cf8f18d79f0b339718d5c0becd4380a22ce2f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e48f874c3e1f031f8cf85a27ed.zip)

**Comment by xurxodev** [comment]
I have not been able to reproduce it

**Comment by ifoche** [comment]
Taking it back to backlog waiting for them to provide more info on how to reproduce it
