### ISSUE TITLE
Update libraries on build.gradle

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#2145]

**Comment by xurxodev** [comment]
We would need to update all libraries versions to the last version possible without needing to touch the code (or at least not too much). Also changing the gradle version when possible would be desirable.

**Comment by ifoche** [comment]
@xurxodev we've just received approval to go ahead with this upgrade (so removing the deprecated stuff)

**Comment by ifoche** [comment]
Please note HNQIS and maintenance labels have been added

**Comment by xurxodev** [comment]
@ifoche I have created issue #2177 to realize this in 1.4 as maintenance issue
