### ISSUE TITLE
zw clone server not working

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2198]
Alpha testers report:

Linda and I have been trying to test HNQIS in the clone.zw.hnqis.org server but the app crashes when we try to start a new survey from the assess module. We are able to start a survey from Plan but not Assess. Please see [the video](https://drive.google.com/file/d/19D17Ka-4wlTXNGIW1M6AenQiFK4KvOfa/view?usp=sharing) of what is happened here. 

We would like to thoroughly test the app with all the health areas but we can't do that because of this issue. 
Also, is the URL generated in the action plan supposed to work on this server?  We get [this error](https://apps.psi-mis.org/hnqis/feedback?eventId=QZb12vyCmFX&server=https://clone-zw.hnqis.org) when we click the link.

**Comment by idelcano** [comment]
The pull of the organisation unit levels is not working for the ZW user.

The api call used by sdk is: https://clone-zw.hnqis.org/api/organisationUnitLevels?fields=id%2CdisplayName%2Clevel&paging=false 
The result of this query is empty for ZW but working for KEdemo1

The 2.30 documentations talks only of the new endpoint filledOrganisationUnitLevels. This is not implemented by sdk, but the ZW can see the organisation unit levels using that endpoint.

https://clone-zw.hnqis.org/api/filledOrganisationUnitLevels?fields=id%2CdisplayName%2Clevel&paging=false

It is possible that the error is from the dhis build.
Another possibility is that some authority is missing.
