### ISSUE TITLE
Bring to 1.4 the login dropdown to select the server

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2224]

**Comment by xurxodev** [comment]
@ifoche @idelcano  In 1.4 we already  have the server dropdown
![server_dropdown.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58178fe4d7adb11300e22349/125516c66e82c728ace21e0d46fb9188358791968bfbb053a052e79a6b0a65633b0ba92e7391a172fd172f07570e1da445505b16aafc8c2aa1b63c718f095ebbd97f4366846c4ff8e7df46f554f832815d84b1b68b49c4ef3826e482864d3d17040ac4.png)

**Comment by xurxodev** [comment]
@idelcano @ifoche this was realized in this PR #2142
