### ISSUE TITLE
Turn new monitoring into a merge between new and old monitoring

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#2370]

**Comment by ifoche** [comment]
From email with Linda...

- Linda Would it be possible to keep some of the monitor module features and still have the new section for tracking action plans? See attached image.
![Monitor module](https://user-images.githubusercontent.com/10931645/70894868-26b07f00-1fee-11ea-8b1b-f3415317fdd3.PNG)

- Nacho: If I understand it properly, you want the new monitor to appear only when the filters are both to "All", so the new monitor wouldn't be filtered. Is that correct? The screenshot shows the bubbles as they were in some versions ago, representing scores and not the competencies. I guess you're meaning the version with the competencies, merged with the new incomplete/complete monitoring functionality...am I correct?

- Linda: Yes, if you select “All Surveys” and “All org units” then the new monitor module should appear that tracks the Action plans (incomplete action plans and complete action plans). Can this be the default page when you open monitor module? Then the old dashboard with pie chart and QoC over the last 6 months can be displayed when you filter by specific health area/org unit just as it was before. (And you are correct, using the version with competency classes, not percentages, thanks for noticing this)

- Nacho: No problem. We will implement that.
