### ISSUE TITLE
first time this screen shows no surveys

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [ifoche/malariapp#2393]
## User Report
unless you create a observation & action plan and then all appear

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot4447258579475013558.jpg)
## Device Info
```
Time Stamp: 2020-01-16T10:30:41 UTC
App Version: 1.5.1 (59)
Install Source: Unknown
Android Version: 8.1.0 (27)
Device Manufacturer: BQ
Device Model: AQUARIS X PRO
Display Resolution: 1920x1080
Display Density (Actual): 408dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by xurxodev** [comment]
@ifoche I have not reproduced this error
