### ISSUE TITLE
Bring v1.5_hnqis to development

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#2421]

**Comment by xurxodev** [comment]
@ifoche In the old days of Android, the normal approach when we started a new version was to bring the changes of the latest release version branch to the development branch. I have tried to do that but the development branch has a last commit at December 2018. I think the development branch has all Questmark features that are many changes, I have found more than 100 conflicts files. So I have been creating a v1.6_hnqis branch from v1.5_hnqis and leaving the decision about the development branch when we can talk together.

**Comment by ifoche** [comment]
Thanks @xurxodev I think we can keep development as-is with the QuestMark issues and I'll be creating a development-hnqis branch and write it to the README of the master branch, so we can remember it in the future. This repo is not supposed to have an intensive development anymore, so it is very likely that we will spend a lot of time before coming back to here again
