### ISSUE TITLE
Implement layout

### ISSUE THREAD

**Issue by adrianq** [ifoche/malariapp#6]

**Comment by adrianq** [comment]
An idea for the draft
![image](https://cloud.githubusercontent.com/assets/6850223/6179655/1642141e-b313-11e4-8123-8c06eed783bd.png)

**Comment by adrianq** [comment]
@ifoche maybe these links can be useful
http://startandroid.ru/en/lessons/complete-list/220-lesson-16-creating-layout-programmatically-layoutparams.html
http://stackoverflow.com/questions/4979212/programmatically-creating-a-relativelayout-in-android

**Comment by josemp10** [comment]
Hiding or showing a component does not seem that complicated

http://stackoverflow.com/questions/5052288/how-can-i-hide-show-an-element-when-a-button-is-pressed

Although I don´t know about the "re-calculation" of the layout. I don´t know if it is better to hide/show or remove/add the components in the layout

**Comment by josemp10** [comment]
@ifoche , this class http://developer.android.com/reference/android/app/ListActivity.html seems a good approach to use as a patern class of our activity/s

**Comment by josemp10** [comment]
(Paso del Ingles). He visto estas dos Views que podrían ser interesantes, yo les estoy echando un ojo a ver...

http://www.androidhive.info/2013/07/android-expandable-list-view-tutorial/

http://www.androidhive.info/2012/10/android-multilevel-listview-tutorial/

**Comment by josemp10** [comment]
Y la última por hoy que habla justamente de Secciones

http://www.iyildirim.com/tech-blog/creating-listview-with-sections
