### ISSUE TITLE
Connect DB outputs to Layout

### ISSUE THREAD

**Issue by adrianq** [ifoche/malariapp#7]

**Comment by josemp10** [comment]
@ifoche , @adrianq I am remembering now that when I worked on the android app for RDF, I found the Android adapters a very good approach to connect different datasources, layouts, and events. I think it is going to be a good idea to use them.

I think we have quite good information here

http://www.vogella.com/tutorials/AndroidListView/article.html

Here in Spanish

http://elbauldelprogramador.com/adapter-personalizado-en-android/

There are many examples in the web

(I am going to try with some examples)
